---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "tv-submit.fullname" . }}
  labels:
    {{- include "tv-submit.labels" . | nindent 4 }}
  creationTimestamp: null
spec:
  tags:
    - annotations:
        openshift.io/imported-from: eformat/tv-submit
      from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
      importPolicy: {}
      name: {{ .Values.image_version }}
